### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by NivixX** [BedwarsRel/BedwarsRel#479]
[23:25:24 INFO]: [BedWars] Initialize database ...
[23:25:24 INFO]: [BedWars] Loading Statistics from Database ...
[23:25:24 WARN]: java.lang.NullPointerException
[23:25:24 WARN]: at io.github.yannici.bedwars.Statistics.PlayerStatisticManager.initializeDatabase(Unknown Source)
[23:25:24 WARN]: at io.github.yannici.bedwars.Statistics.PlayerStatisticManager.initialize(Unknown Source)
[23:25:24 WARN]: at io.github.yannici.bedwars.Main.loadStatistics(Unknown Source)
[23:25:24 WARN]: at io.github.yannici.bedwars.Main.onEnable(Unknown Source)
[23:25:24 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:25:24 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[23:25:24 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[23:25:24 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[23:25:24 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[23:25:24 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[23:25:24 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[23:25:24 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[23:25:24 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[23:25:24 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[23:25:24 WARN]: at java.lang.Thread.run(Thread.java:745)
[23:25:24 INFO]: [BedWars] Done.

[http://image.noelshack.com/fichiers/2016/14/1459805026-screenshot-7.png](url)

Can you help me please ?
I already have a database and set up the config.yml

:'(

**Comment by sebastianbinder** [comment]
Hi @NivixX 
Just to get more details: Is there any statistic in you database yet? So is the table from Bedwars-Reloaded there?

**Comment by NivixX** [comment]
Thank you for your help ;)

I Created an "rush" database on my mysql server ( the database is empty ).
And I configured the config.yml with the user of the mysql, the database name and the ip of the server.
I have put "database" on the config.yml to.

Thank you.

**Comment by NivixX** [comment]
The problem is that when I put other thing than "localhost" in the mysql config, I have this error 

http://pastebin.com/7HiKFK0K

**Comment by sebastianbinder** [comment]
Hi. As soon as you are not using MySQL your user doesn't have permission to access the server anymore. That's good. You should access it via ``localhost`` or even better ``127.0.0.1``.
Actually I have no clue what's causing you database issues. Maybe @Yannici can tell you more…
