### ISSUE TITLE
ProtectionWall

### ISSUE THREAD

**Issue by sebastianbinder** [BedwarsRel/BedwarsRel#513]
Works in general, but the stone brick block doesn't get removed and the following error is thrown:
```
[13:16:41 ERROR]: Could not pass event BlockPlaceEvent to BedwarsRel v1.3.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.ItemStack.placeItem(ItemStack.java:165) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:522) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
        at io.github.yannici.bedwars.Shop.Specials.ProtectionWallListener.onPlace(ProtectionWallListener.java:67) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2-2016-04-24-01.jar:git-Spigot-e6f93f4-7a6b143]
        ... 18 more
```
Lines 67-69:
```java
if(place.getItemInHand().getItemMeta().getDisplayName() == null){
  return;
}
```
``getItemMeta()`` might be null… Need to check on it.

**Comment by sebastianbinder** [comment]
Current status: Brick block is being placed, protection wall appears, no NPE, but brick block is not getting removed.
