### ISSUE TITLE
Check Spawner Particles

### ISSUE THREAD

**Issue by sebastianbinder** [BedwarsRel/BedwarsRel#643]
Questions: Reflection still needed for latest Minecraft-versions? Might there be a way in the API? What is this error about? With this error TPS are dropping extremely.

``` yml
[20:23:17 WARN]: java.lang.ClassNotFoundException: io.github.bedwarsrel.BedwarsRel.Com.Fallback.ParticleSpawner
[20:23:17 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[20:23:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[20:23:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:23:17 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:23:17 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:23:17 WARN]:        at java.lang.Class.forName0(Native Method)
[20:23:17 WARN]:        at java.lang.Class.forName(Class.java:264)
[20:23:17 WARN]:        at io.github.bedwarsrel.BedwarsRel.Utils.createParticleInGame(Utils.java:106)
[20:23:17 WARN]:        at io.github.bedwarsrel.BedwarsRel.Shop.Specials.WarpPowder$1.run(WarpPowder.java:166)
[20:23:17 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
[20:23:17 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:23:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
[20:23:17 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[20:23:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[20:23:17 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[20:23:17 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Monster6** [comment]
Sebastianbinder can you please check on the issue i am having? Thanks

**Comment by Yannici** [comment]
Used to create single particles for the teleport special item.

**Comment by Monster6** [comment]
Yannici can you comment on my thread please? Heres what it basically says reply here So whenever i start the game up everything works fine until a person fall into the void. Then they teleport to the world spawn instead of their players team. Please help thanks
