### ISSUE TITLE
Not compatible with RankPrefixPlus

### ISSUE THREAD

**Issue by GamerBrownie2** [BedwarsRel/BedwarsRel#653]
When i use RankPrefixPlus and BedWars-Rel in the game lobby it spams this error:
```
[BedwarsRel] Task #109 for BedwarsRel v1.3.3 generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253) ~[spigot-latest.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftTeam.getPlayers(CraftTeam.java:110) ~[spigot-latest.jar:git-Spigot-570526c-75a8885]
        at io.github.bedwarsrel.BedwarsRel.Game.Team.getPlayers(Team.java:157) ~[?:?]
        at io.github.bedwarsrel.BedwarsRel.Game.Game.getTeamPlayers(Game.java:1474) ~[?:?]
        at io.github.bedwarsrel.BedwarsRel.Shop.Specials.Tracker$1.run(Tracker.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-latest.jar:git-Spigot-570526c-75a8885]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-latest.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-latest.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-latest.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-latest.jar:git-Spigot-570526c-75a8885]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-latest.jar:git-Spigot-570526c-75a8885]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by sebastianbinder** [comment]
Unfortunately it is simply impossible to provide compatibility with any plugin that is out there. We might be able to change our code a little bit, if this was an improvement for the majority of server owners. But as we are maintaining this repository in our free time, we cannot further investigate here, so as long as there isn't a major bug being caused by BedwarsRel, we cannot help you :/
