### ISSUE TITLE
Error While Enableing plugin 

### ISSUE THREAD

**Issue by Pattanawaris** [BedwarsRel/BedwarsRel#659]
(using spigot 1.10.2)
======================
[16:28:49 ERROR]: Could not call constructor 'public io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner(java.util.Map)' of class io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner for deserialization
java.lang.NullPointerException
        at io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner.<init>(RessourceSpawner.java:36) ~[?:?]
        at sun.reflect.GeneratedConstructorAccessor55.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_77]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_77]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:96) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:133) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:470) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at io.github.bedwarsrel.BedwarsRel.Game.GameManager.loadGame(GameManager.java:162) [BedwarsRel-1.3.3.jar:?]
        at io.github.bedwarsrel.BedwarsRel.Game.GameManager.loadGames(GameManager.java:142) [BedwarsRel-1.3.3.jar:?]
        at io.github.bedwarsrel.BedwarsRel.Main.onEnable(Main.java:175) [BedwarsRel-1.3.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[16:28:49 ERROR]: Could not call constructor 'public io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner(java.util.Map)' of class io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner for deserialization
java.lang.NullPointerException
        at io.github.bedwarsrel.BedwarsRel.Game.RessourceSpawner.<init>(RessourceSpawner.java:36) ~[?:?]
        at sun.reflect.GeneratedConstructorAccessor55.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_77]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_77]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:96) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:133) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:470) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at io.github.bedwarsrel.BedwarsRel.Game.GameManager.loadGame(GameManager.java:162) [BedwarsRel-1.3.3.jar:?]
        at io.github.bedwarsrel.BedwarsRel.Game.GameManager.loadGames(GameManager.java:142) [BedwarsRel-1.3.3.jar:?]
        at io.github.bedwarsrel.BedwarsRel.Main.onEnable(Main.java:175) [BedwarsRel-1.3.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by sebastianbinder** [comment]
There is an error with your spawner configuration. Easiest thing would be resetting your config files and start over again.
