### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by Moritz77** [BedwarsRel/BedwarsRel#670]
Wenn ich das erstemal den start button drücke kommt in der console:

[15:34:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BedwarsRel v1.3.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:227) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftTeam.getEntries(CraftTeam.java:123) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at io.github.yannici.bedwars.Game.Team.getPlayers(Team.java:158) ~[?:?]
	at io.github.yannici.bedwars.Game.Game.getPlayers(Game.java:1468) ~[?:?]
	at io.github.yannici.bedwars.Game.Game.broadcast(Game.java:842) ~[?:?]
	at io.github.yannici.bedwars.Game.Game.start(Game.java:229) ~[?:?]
	at io.github.yannici.bedwars.Listener.PlayerListener.onPlayerInteract(PlayerListener.java:937) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	... 16 more

UND NIX PASSIERT!

**Comment by Yannici** [comment]
Hi. Wir bräuchten an dieser Stelle mehr Details von dir. Also schau doch bitte mal auf https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue und lass uns so viel wie möglich über dein Setup wissen.

**Comment by sebastianbinder** [comment]
Neuigkeiten?
