### ISSUE TITLE
Bug with new items.

### ISSUE THREAD

**Issue by TheIntelloBox** [BedwarsRel/BedwarsRel#691]
Hello,

[19:50:09] [Server thread/INFO]: [BedwarsRel] Enabling BedwarsRel v1.3.4
[19:50:10] [Server thread/WARN]: java.lang.RuntimeException: Unable to override the old entity RegistryMaterials
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Com.v1_11_R1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:51)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Com.v1_11_R1.CustomEntityRegistry.addCustomEntity(CustomEntityRegistry.java:59)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Com.v1_11_R1.TNTSheepRegister.registerEntities(TNTSheepRegister.java:26)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Shop.Specials.TNTSheepListener.<init>(TNTSheepListener.java:30)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Shop.Specials.SpecialItem.loadSpecials(SpecialItem.java:38)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Main.registerListener(Main.java:713)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Main.onEnable(Main.java:166)
[19:50:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[19:50:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[19:50:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:50:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[19:50:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[19:50:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
[19:50:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
[19:50:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
[19:50:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[19:50:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[19:50:10] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:50:10] [Server thread/WARN]: Caused by: java.lang.IllegalAccessException: Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to io.github.bedwarsrel.BedwarsRel.Com.v1_11_R1.CustomEntityRegistry
[19:50:10] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source)
[19:50:10] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source)
[19:50:10] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(Unknown Source)
[19:50:10] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[19:50:10] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.Com.v1_11_R1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:47)
[19:50:10] [Server thread/WARN]: 	... 17 more

http://hastebin.com/govajisici

Thanks to help me. :D

**Comment by sebastianbinder** [comment]
Really man, you need to work on your setup and your work attitude. It's always you reporting bugs that are no bugs or being caused by your really bad setup. Furthermore you are just sending a Spigot 1.11 stack trace. No information if there is a problem at all and then adding a link to hastebin stating a 1.8.8 server setup. We can only help you if you work properly and provide the right details. But just spamming issues does not make sense.

**Comment by TheIntelloBox** [comment]
Sorry, I did a mistake, I'm in 1.11. But can you help me please ?

**Comment by sebastianbinder** [comment]
I can help you if there is still an issue after having removed each and every plugin except BedwarsRel and its dependencies and running latest Spigot build from BuildTools.

**Comment by TheIntelloBox** [comment]
But my server is on a host so how can I use the buildtools ?

**Comment by sebastianbinder** [comment]
I cannot help you in terms of how to use latest server versions. As a server owner you are supposed to have enough knowledge about administration.

**Comment by TheIntelloBox** [comment]
But, is my problem a problem with the new names of the entity, or an error of BedwarsRel ?

**Comment by sebastianbinder** [comment]
As I cannot reproduce your problem I cannot tell you.

**Comment by TheIntelloBox** [comment]
Could you tell me if my shop.yml has old items ?
http://hastebin.com/ojadonatip.scala

**Comment by sebastianbinder** [comment]
What do you mean by "old items"? Furthermore we are just supporting our default shop.yml and providing help with adding additional items to this file. We are not able to check each and every config if there is anything wrong with it.

**Comment by TheIntelloBox** [comment]
The ID and the name of some items are changed in 1.11. 
Could you tell me what do you see in the error ?

**Comment by sebastianbinder** [comment]
First of all I don't see any error. Just a warning. It says `Unable to override the old entity RegistryMaterials`. As you are still not providing any proper information about your setup and you are still not doing those things I requested before, I cannot help you.

**Comment by TheIntelloBox** [comment]
Okay, what do you want ?

The version : git-Spigot-261f181-7359112 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
Version of Bedwars Rel : 1.3.4.

**Comment by sebastianbinder** [comment]
Read my first and second comment on this issue!

**Comment by TheIntelloBox** [comment]
I did it with the build tool and there is the bug.

**Comment by sebastianbinder** [comment]
You ignored the first part of my second comment. Furthermore `git-Spigot-261f181-7359112` is one week old.

**Comment by sebastianbinder** [comment]
And don't forget about the `/bw debugpaste`…

**Comment by TheIntelloBox** [comment]
Works fine. :D Thanks a lot.
