### ISSUE TITLE
pls help me 

### ISSUE THREAD

**Issue by PetteRed65** [BedwarsRel/BedwarsRel#713]
I am opening a minecraft server with your plugin, but when i start the server i found this error:
[10:56:58 INFO]: [BedWars] Couldn't find version related class io.github.yannici.bedwars.Com.v1_11_R1.TNTSheepRegister
[10:56:58 WARN]: java.lang.NullPointerException
[10:56:58 WARN]:        at io.github.yannici.bedwars.Shop.Specials.TNTSheepListener.<init>(TNTSheepListener.java:31)
[10:56:58 WARN]:        at io.github.yannici.bedwars.Shop.Specials.SpecialItem.loadSpecials(SpecialItem.java:68)
[10:56:58 WARN]:        at io.github.yannici.bedwars.Main.registerListener(Main.java:662)
[10:56:58 WARN]:        at io.github.yannici.bedwars.Main.onEnable(Main.java:146)
[10:56:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[10:56:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[10:56:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:56:58 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[10:56:58 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[10:56:58 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
[10:56:58 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
[10:56:58 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
[10:56:58 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[10:56:58 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[10:56:58 WARN]:        at java.lang.Thread.run(Thread.java:745)

please help me if you can

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by PetteRed65** [comment]
Version of BedwarsRel: 1.3.4
Verision of Spigot: 1.11 
Server Setup: Single server
Installed Plugin:
- All the essentials plugin except essentials GeoIP
- Multiverse-Core
- Pex
- WorldGuard
- BedwarsRel
- WorldEdit
I will haven't changed anything in the shop and in the config file
The console error is in the first comment
The problem is i can't use the tnt sheep

**Comment by sebastianbinder** [comment]
Please give us the exact Spigot version (including the git commit version hash)

**Comment by sebastianbinder** [comment]
"io.github.yannici" in the stack trace doesn't look like you are using BedwarsRel 1.3.4

**Comment by PetteRed65** [comment]
because I downloaded it on the site I use for the server, not on my comupter


2017-01-09 9:00 GMT+01:00 Sebastian Binder <notifications@github.com>:

**Comment by sebastianbinder** [comment]
Sorry I'm not able to understand you. If you do not provide the details we need and do not keep your plugin up to date, I cannot help you.
