### ISSUE TITLE
NoSuchMethodError due to not relocating shaded dependencies

### ISSUE THREAD

**Issue by RoboMWM** [BedwarsRel/BedwarsRel#733]
Sure, could also be the fault of the mysterious other plugin that decided to shade and include a different version of fasterxml or w/e the dependency is...

I also had another issue with slf4j, but this was on a test server with a plugin I don't use on my production server, so I just removed its conflicting class.

So, it'd help you guys out to relocate the stuff you shade and avoid conflicts with other plugins.

```
[18:38:39] [Server thread/ERROR]: Error occurred while enabling BedwarsRel v1.3.4-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:537) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:448) ~[?:?]
	at com.bugsnag.serialization.Serializer.<init>(Serializer.java:11) ~[?:?]
	at com.bugsnag.Configuration.<init>(Configuration.java:29) ~[?:?]
	at com.bugsnag.Bugsnag.<init>(Bugsnag.java:41) ~[?:?]
	at com.bugsnag.Bugsnag.<init>(Bugsnag.java:27) ~[?:?]
	at io.github.bedwarsrel.BedwarsRel.Main.registerBugsnag(Main.java:198) ~[?:?]
	at io.github.bedwarsrel.BedwarsRel.Main.onEnable(Main.java:132) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1062]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by sebastianbinder** [comment]
Hi @RoboMWM,
I just relocated our dependencies to another package. Please check on the dev-build on https://3064-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.5-SNAPSHOT.jar and provide feedback if it works as expected.

**Comment by RoboMWM** [comment]
Seems to be loading up now, thanks!
