### ISSUE TITLE
com/bugsnag/callbacks/Callback : NoClassDefFound

### ISSUE THREAD

**Issue by GitGraf** [BedwarsRel/BedwarsRel#756]
Hello, so I wanted to take a look at this project and _maybe_ code some features, but when I re-compiled the BedwarsRel Project into a jar file and tried to start up the server, I get a NoClassDefFoundError:

org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: **com/bugsnag/callbacks/Callback**
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/bugsnag/callbacks/Callback
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        ... 6 more
Caused by: **java.lang.ClassNotFoundException: com.bugsnag.callbacks.Callback**
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]

Did this class get moved somewhere? Or am I missing out on something?
Best regards

**Comment by sebastianbinder** [comment]
Simply build it - maven should handle everything.
