### ISSUE TITLE
on end game

### ISSUE THREAD

**Issue by xCraftRayX** [BedwarsRel/BedwarsRel#782]
[01:33:03 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '390df42e-2b7f-3578-8158-0b492be912b3' for key 'uuid'
[01:33:03 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:33:03 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:33:03 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:33:03 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:33:03 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[01:33:03 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[01:33:03 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
[01:33:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[01:33:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[01:33:03 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[01:33:03 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[01:33:03 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[01:33:03 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[01:33:03 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[01:33:03 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[01:33:03 WARN]:        at com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:410)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Database.DatabaseManager.update(DatabaseManager.java:219)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Statistics.PlayerStatisticManager.storeDatabaseStatistic(PlayerStatisticManager.java:171)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Statistics.PlayerStatisticManager.storeStatistic(PlayerStatisticManager.java:112)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Statistics.PlayerStatistic.store(PlayerStatistic.java:263)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Game.Game.playerLeave(Game.java:816)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Game.GameCycle.onPlayerRespawn(GameCycle.java:302)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Listener.PlayerListener.onPlayerRespawn(PlayerListener.java:295)
[01:33:03 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:33:03 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:33:03 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:33:03 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:33:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[01:33:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:33:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[01:33:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.moveToWorld(PlayerList.java:624)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.moveToWorld(PlayerList.java:552)
[01:33:03 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer$1.respawn(CraftPlayer.java:1492)
[01:33:03 WARN]:        at io.github.bedwarsrel.BedwarsRel.Listener.PlayerListener$2.run(PlayerListener.java:342)
[01:33:03 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[01:33:03 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[01:33:03 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[01:33:03 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by akashaggarwal7** [comment]
Your database table already has an entry of that UUID. Perhaps you're in offline mode and 2 players have the same UUID(which is VERY VERY VERY unlikely).

**Comment by sebastianbinder** [comment]
As with the upcoming version (1.3.5) the MySQL-system has completely been rewritten. So I cannot tell you if this has been fixed, as too much code has been changed. I'll close this one and would like to ask you to tell me if this has been fixed in the new version (after its release).
