### ISSUE TITLE
BedwarsRel 1.3.5 - Testing

### ISSUE THREAD

**Issue by sebastianbinder** [BedwarsRel/BedwarsRel#787]
Hey guys,
for the upcoming update (compatible with Spigot 1.12) I need some testers. **No, you are not supposed to use this on your production servers!!!!** Please provide feedback in the comments below - I try to make everything compatible as fast as possible.

# Known Issues
- Colors of beds not working

# Download
- [2017-06-10 - 15:36 - 2dc26b7](https://3883-32877020-gh.circle-artifacts.com/0/artifacts/BedwarsRel-1.3.5-SNAPSHOT.jar)

**Comment by Latouth** [comment]
ETA on release date?

**Comment by sebastianbinder** [comment]
There is not even a final spigot release date so far??

**Comment by Latouth** [comment]
Nah, you can still get it out for 1.11 spigot then update to 1.12

On May 18, 2017 12:11 AM, "Sebastian Binder" <notifications@github.com>
wrote:

There is not even a final spigot release date so far??

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BedwarsRel/BedwarsRel/issues/787#issuecomment-302295497>,
or mute the thread

**Comment by MystServer** [comment]
I take it that download link has no purpose currently and is intended to be used on a 1.12 non-production server once 1.12 is officially released and spigot updates?

**Comment by sebastianbinder** [comment]
BedwarsRel 1.3.5 is going to be released as soon as final Spigot 1.12 will be available. The download link is for public testing as this helps me a lot about finding errors which might be there...

**Comment by akashaggarwal7** [comment]
I'd like to help

**Comment by sebastianbinder** [comment]
@akashaggarwal7 just download via the link above

**Comment by ErkePannekake** [comment]
il be testing it, i have allways been happy with the bedwarsrel support, helped me of total 2 times on the plugin, the developer is allways nice and much better than the PermissionsEx dev who told me to fck off since im stupid lol

**Comment by TheIntelloBox** [comment]
So ? 1.12 is out.

**Comment by sebastianbinder** [comment]
Link is above. Don't know about a release date so far.

**Comment by TheIntelloBox** [comment]
This weekend ?

**Comment by 1337hOlY** [comment]
/bw setspawner <gamename> <bronze/iron/gold> dont work in this beta.

**Comment by sebastianbinder** [comment]
Thank you. I just fixed it - link is updated to new build

**Comment by TheIntelloBox** [comment]
[09:51:49] [Server thread/INFO]: [Spdc Rush] *** Warning, you are using a development build ***
[09:51:49] [Server thread/INFO]: [Spdc Rush] *** You will get NO support regarding this build ***
[09:51:49] [Server thread/INFO]: [Spdc Rush] *** Please download a stable build from https://github.com/BedwarsRel/BedwarsRel/releases ***
[09:51:49] [Server thread/INFO]: [Spdc Rush] *** Server will start in 10 seconds ***
[09:52:00] [Server thread/WARN]: java.lang.RuntimeException: Unable to override the old entity RegistryMaterials
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.com.v1_12_r1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:56)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.com.v1_12_r1.CustomEntityRegistry.addCustomEntity(CustomEntityRegistry.java:32)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.com.v1_12_r1.TNTSheepRegister.registerEntities(TNTSheepRegister.java:24)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.shop.Specials.TNTSheepListener.<init>(TNTSheepListener.java:30)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.shop.Specials.SpecialItem.loadSpecials(SpecialItem.java:38)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.registerListener(BedwarsRel.java:897)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.BedwarsRel.onEnable(BedwarsRel.java:791)
[09:52:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:52:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[09:52:00] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
[09:52:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[09:52:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[09:52:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[09:52:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[09:52:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[09:52:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[09:52:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[09:52:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[09:52:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[09:52:00] [Server thread/WARN]: Caused by: java.lang.IllegalAccessException: Can not set static final net.minecraft.server.v1_12_R1.RegistryMaterials field net.minecraft.server.v1_12_R1.EntityTypes.b to io.github.bedwarsrel.com.v1_12_r1.CustomEntityRegistry
[09:52:00] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[09:52:00] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[09:52:00] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
[09:52:00] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[09:52:00] [Server thread/WARN]: 	at io.github.bedwarsrel.com.v1_12_r1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:52)
[09:52:00] [Server thread/WARN]: 	... 18 more

**Comment by sebastianbinder** [comment]
Which Spigot build are you using?

**Comment by TheIntelloBox** [comment]
git-Spigot-d5dfb24-ed8c725 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by sebastianbinder** [comment]
I cannot reproduce this :/

**Comment by sebastianbinder** [comment]
https://github.com/BedwarsRel/BedwarsRel/releases/tag/v1.3.5
