### ISSUE TITLE
HolographicDisplay Issue

### ISSUE THREAD

**Issue by BOOM21** [BedwarsRel/BedwarsRel#811]
Happens right after the first Player joins the Server where BedWarsRel is running on. I think it might be a Bug in maths or something. Would be great if you fix it. In cause of this, the Hologramm does not generate.

[17:04:45 WARN]: [BedwarsRel] Task #147 for BedwarsRel v1.3.5 generated an exception
java.lang.NumberFormatException: For input string: "1,27"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_66]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_66]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_66]
        at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_66]
        at io.github.bedwarsrel.statistics.PlayerStatistic.getCurrentKD(PlayerStatistic.java:122) ~[?:?]
        at io.github.bedwarsrel.statistics.PlayerStatisticManager.createStatisticLines(PlayerStatisticManager.java:57) ~[?:?]
        at io.github.bedwarsrel.HolographicDisplaysInteraction.updatePlayerStatisticHologram(HolographicDisplaysInteraction.java:286) ~[?:?]
        at io.github.bedwarsrel.HolographicDisplaysInteraction.createPlayerStatisticHologram(HolographicDisplaysInteraction.java:39) ~[?:?]
        at io.github.bedwarsrel.HolographicDisplaysInteraction.updatePlayerHologram(HolographicDisplaysInteraction.java:255) ~[?:?]
        at io.github.bedwarsrel.HolographicDisplaysInteraction.access$300(HolographicDisplaysInteraction.java:23) ~[?:?]
        at io.github.bedwarsrel.HolographicDisplaysInteraction$3.run(HolographicDisplaysInteraction.java:229) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by sebastianbinder** [comment]
Should be fixed with https://github.com/BedwarsRel/BedwarsRel/commit/75d0ffa71167b7a80b839bf8caf2b881ab66bbc2#diff-db8956c771d3e5aa4560879e7f6ebd10 and will be in next release (or in the latest dev-builds)
