### ISSUE TITLE
Players being repeatedly disconnected due to "Unknown mob network type id -1"

### ISSUE THREAD

**Issue by RoboMWM** [BedwarsRel/BedwarsRel#834]
When teleporting to a world used by Bedwars, the plugin does _something_ that causes the player to be kicked. The player sees the message "Disconnected." In console:

```
[13:32:39] [Netty Server IO #3/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.12.jar:git-Paper-1150]
MMM10 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1
```

The player is continually disconnected a second after reconnecting.

Upon disabling BedwarsRel, the player is no longer kicked when entering the world or reconnecting in the world.

Will get more info if needed, kind of in a hurry right now. Using paper 1.12, Bedwars 1.3.5-SNAPSHOT (thought I switched back to master branch, will have to doublecheck that). Protocolsupport is on the server, but the client is 1.12.

**Comment by RoboMWM** [comment]
Still present on 1.3.6.

```
[12:56:04] [Netty Server IO #3/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.12.jar:git-Paper-1152]
[12:56:04] [Server thread/INFO]: MMM10 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1
```

**Comment by sebastianbinder** [comment]
Sorry, I really have no idea about this one.

**Comment by RoboMWM** [comment]
I'll try testing on a test server (just the world, bedwars plugin and datafolder) but unsure when I'll be able to get to it this week. I could also send you these as well.

**Comment by RoboMWM** [comment]
I don't think BlockBall was installed when this issue appeared, but it seems this plugin attempts to register all entities via reflection? Interestingly it's having trouble with an entity you create/is related to your plugin:

```
[21:55:51] [Server thread/INFO]: [BlockBall] Enabling BlockBall v4.0.1
[21:55:51] [Server thread/INFO]: [BlockBall] Loading BlockBall ...
[21:55:51] [Server thread/WARN]: Failed to register entity!
java.lang.NoSuchMethodException: io.github.bedwarsrel.com.v1_12_r1.CustomEntityRegistry.a(int, java.lang.Object, java.lang.Object)
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_131]
	at com.github.shynixn.blockball.lib.LightRegistry$WrappedEntityRegistry.modify(LightRegistry.java:112) ~[BlockBall.jar:?]
	at com.github.shynixn.blockball.lib.LightRegistry$WrappedEntityRegistry.registerCustomEntity(LightRegistry.java:83) ~[BlockBall.jar:?]
	at com.github.shynixn.blockball.lib.LightRegistry.register(LightRegistry.java:58) [BlockBall.jar:?]
	at com.github.shynixn.blockball.lib.LightRegistry.register(LightRegistry.java:50) [BlockBall.jar:?]
	at com.github.shynixn.blockball.business.bukkit.nms.NMSRegistry.registerAll(NMSRegistry.java:90) [BlockBall.jar:?]
	at com.github.shynixn.blockball.business.bukkit.BlockBallPlugin.reload(BlockBallPlugin.java:67) [BlockBall.jar:?]
	at com.github.shynixn.blockball.business.bukkit.BlockBallPlugin.onEnable(BlockBallPlugin.java:32) [BlockBall.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.jar:git-Paper-1152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1152]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [patched_1.12.jar:git-Paper-1152]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1152]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1152]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1152]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1152]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1152]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1152]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[21:55:52] [Server thread/INFO]: [BlockBall] found dependency [WorldGuard] 5.
[21:55:52] [Server thread/INFO]: [BlockBall] failed to hook into [WorldGuard] 5.
[21:55:52] [Server thread/INFO]: [BlockBall] found dependency [WorldGuard] 6.
[21:55:52] [Server thread/INFO]: [BlockBall] hooked successfully into [WorldGuard] 6.
[21:55:52] [Server thread/INFO]: [BlockBall] found dependency [Vault].
[21:55:52] [Server thread/INFO]: [BlockBall] hooked successfully into [Vault].
[21:55:52] [Server thread/INFO]: [BlockBall] Enabled BlockBall 4.0.1 by Shynixn
```

**Comment by RoboMWM** [comment]
Ok, so far discovered that it occurs when the stats hologram is added. Upon some fun delete some plugins and test with the test server, the problem has been isolated to a conflict with the citizens plugin. It appears the moment bedwars spawns the hologram (or whatever else it does during that - the hologram), it causes the player to disconnect.

So... now to figure out why citizens is having issues with your plugin... for reference, citizens plugin version 2.0.22 (build 1487)

**Comment by RoboMWM** [comment]
To reproduce:

- 1.12 server with bedwarsrel v1.3.6, citizens v2.0.22 (build 1487), HolographicDisplays and Protocollib.
- Create a bedwars stats hologram via `/bw addholo`

**Comment by RoboMWM** [comment]
For reference, from the referenced issue:

mcmonkey4eva:
> Citizens overrides the entity mapping in a careful way, designed to leave room for other plugins to do the same. However if other plugins are less clever, it can cause problems.
 Don't know if that's the case, but that's probably the first option to investigate.

Considering that BlockBall has issues registering an entity of yours, my guess is that the issue lies within this repo. (I haven't messed with entity mapping or the like, so not sure what to look for).
