### ISSUE TITLE
BedwarsRel Enable Error with version 1.3.6, -.5, -.4

### ISSUE THREAD

**Issue by IxonTV** [BedwarsRel/BedwarsRel#842]
I've only tried these three versions yet, but it gives always the same Error. I've got a 1.8 Spigot Server.
Error Code:
[21:57:05 INFO]: [BedwarsRel] Enabling BedwarsRel v1.3.6
[21:57:06 ERROR]: Error occurred while enabling BedwarsRel v1.3.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.potion.PotionEffect.<init>(Lorg/bukkit/potion/PotionEffectType;IIZZ)V
at io.github.bedwarsrel.updater.ConfigUpdater.addConfigs(ConfigUpdater.java:238) ~[?:?]
at io.github.bedwarsrel.BedwarsRel.onEnable(BedwarsRel.java:775) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:498) [craftbukkit.jar:git-Spigot-da32fe1-df0b4c1]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

I don't know whats the Problem... when i make /plugins BedwarsRel is Green and when i make /bw help it only says "/bw help"... I've tested version 1.3.6 on another Server. The same.(1.8)

**Comment by sebastianbinder** [comment]
Hi. We need some more details from you. Please have a look on https://github.com/BedwarsRel/BedwarsRel/wiki/HowTo:-Write-an-Issue and let us know as much as possible about your setup.

**Comment by IxonTV** [comment]
Now i've made my issue much better, can you please Check it again?

**Comment by sebastianbinder** [comment]
Ah I can see the error. It’s because 1.8 is a pretty old version of Minecraft. If I have time for that, I’ll fix it.

**Comment by IxonTV** [comment]
Thank you very much :3! When its fixed, you get a 5 stars Rating :P!!!!

**Comment by sebastianbinder** [comment]
When you update your server to 1.12 you’ll get a 5 star rating from me :D

**Comment by IxonTV** [comment]
Oh shit, then i have to update 30 Plugins on 1.12 :D... i See what i can do :P! Are you from Germany 0.o?

**Comment by IxonTV** [comment]
Finally i've got one question:
When you in the future fix the bug, comes it with an Update?

Cu

**Comment by sebastianbinder** [comment]
> When you in the future fix the bug, comes it with an Update?

Of course?

**Comment by sebastianbinder** [comment]
Oh I am sorry. Forget about my comments before. It seems like I am bad at counting. So I don't really see the issue.   
The error you are talking about corresponds to the following line:  
```java
new PotionEffect(PotionEffectType.BLINDNESS, 5 * 20, 2, true, true)
```
I just compiled Spigot in 1.8 and there is the following constructor:
```java
    /**
     * Creates a potion effect.
     * @param type effect type
     * @param duration measured in ticks, see {@link
     *     PotionEffect#getDuration()}
     * @param amplifier the amplifier, see {@link PotionEffect#getAmplifier()}
     * @param ambient the ambient status, see {@link PotionEffect#isAmbient()}
     * @param particles the particle status, see {@link PotionEffect#hasParticles()}
     */
    public PotionEffect(PotionEffectType type, int duration, int amplifier, boolean ambient, boolean particles){
        Validate.notNull(type, "effect type cannot be null");
        this.type = type;
        this.duration = duration;
        this.amplifier = amplifier;
        this.ambient = ambient;
        this.particles = particles;
    }
```
So everything should be fine here. I also found out, that even your old 1.8 version is not the latest 1.8 version available. Have you tried using latest 1.8 (cause that's the one I just compiled)?

**Comment by IxonTV** [comment]
I bought my Server on Nitrado.net and i think its the latest 1.8 Version
