### ISSUE TITLE
Database - Error

### ISSUE THREAD

**Issue by flixoflax** [BedwarsRel/BedwarsRel#873]
Hikari is not working with Java 8!!! 
Please fix the MySQL - System!

**Comment by sebastianbinder** [comment]
Hikari with Java 8 is working perfectly on my server.

**Comment by flixoflax** [comment]
why am i getting this error then?:

[19:45:56] [Server thread/ERROR]: Error occurred while enabling BedwarsRel v1.3.6 (Is it up to date?)
thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:528) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.checkFailFast(HikariPool.java:520) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.<init>(HikariPool.java:112) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.HikariDataSource.<init>(HikariDataSource.java:72) ~[?:?]
	at io.github.bedwarsrel.database.DatabaseManager.initialize(DatabaseManager.java:43) ~[?:?]
	at io.github.bedwarsrel.BedwarsRel.loadDatabase(BedwarsRel.java:668) ~[?:?]
	at io.github.bedwarsrel.BedwarsRel.onEnable(BedwarsRel.java:788) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.PoolBase.newConnection(PoolBase.java:341) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499) ~[?:?]
	... 16 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'bedwars'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.PoolBase.newConnection(PoolBase.java:341) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428) ~[?:?]
	at thirdparty.com.zaxxer.HikariCP-java7.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499) ~[?:?]
	... 16 more
