### ISSUE TITLE
1.13 error

### ISSUE THREAD

**Issue by PhanaticD** [BedwarsRel/BedwarsRel#960]
```
[07:44:31] [Server thread/INFO]: Enabling BedwarsRel v1.3.6*
[07:44:31] [Server thread/INFO]: [BedWars] Couldn't find version related class io.github.bedwarsrel.com.v1_13_R2.TNTSheepRegister
[07:44:31] [Server thread/WARN]: java.lang.NullPointerException
[07:44:31] [Server thread/WARN]:    at io.github.bedwarsrel.shop.Specials.TNTSheepListener.<init>(TNTSheepListener.java:29)
[07:44:31] [Server thread/WARN]:    at io.github.bedwarsrel.shop.Specials.SpecialItem.loadSpecials(SpecialItem.java:38)
[07:44:31] [Server thread/WARN]:    at io.github.bedwarsrel.BedwarsRel.registerListener(BedwarsRel.java:897)
[07:44:31] [Server thread/WARN]:    at io.github.bedwarsrel.BedwarsRel.onEnable(BedwarsRel.java:791)
[07:44:31] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[07:44:31] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[07:44:31] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:44:31] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[07:44:31] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[07:44:31] [Server thread/WARN]:    at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[07:44:31] [Server thread/WARN]:    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[07:44:31] [Server thread/WARN]:    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[07:44:31] [Server thread/WARN]:    at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[07:44:31] [Server thread/WARN]:    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[07:44:31] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

```

**Comment by PhanaticD** [comment]
will there be support in the future?

**Comment by Boy132** [comment]
I don't think so. At least not from the current devs.

**Comment by sebastianbinder** [comment]
I will start working on it after finishing my final exams in March.

**Comment by Boy132** [comment]
Hej, glad you're alive. :D

**Comment by TheIntelloBox** [comment]
March, lul, 1.14 will be released. xD
