### ISSUE TITLE
stats_players primary key exceeds max key length of 767 bytes

### ISSUE THREAD

**Issue by Oshgnacknak** [BedwarsRel/BedwarsRel#963]
Hello dear BedWarsRel-Team,

I think I found a bug regarding the sql-handling of yours:

I'm running `BedwarsRel version 1.3.6`, the config is attached, and `mariadb  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2` and tried out to set up a statistics-database.
[bedwarsrel-config.yml.txt](https://github.com/BedwarsRel/BedwarsRel/files/2809527/bedwarsrel-config.yml.txt)

After initializing the database via phpmyadmin and running a bedwars-server with the new config, i got this  exception:
```[29.01.2019 20:16:18] INFO: [BedWars-1] [19:58:35 INFO]: [BedWars] Loading statistics from database ...
[29.01.2019 20:16:18] INFO: [BedWars-1] [19:58:35 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
[29.01.2019 20:16:18] INFO: [BedWars-1] [19:58:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[29.01.2019 20:16:18] INFO: [BedWars-1] [19:58:35 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
< more stack trace >
```

I looked up this error and found out that varchar(255) is to big for a primary key: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes. The internet also told me that createing the table myself manualy may resolve my problems, so I searched Your sourcecode for the sql-command to create the table. I ran that on my database, first with and than without the primeray key, succeeding at my second try, without the key option. I also tested to play a game and get a death counting. It worked, another server recognized my defeat using the same database.

By this I conclude that the primery key is irrelevant and can be skipped, so nobody has to create the table by hand.

Thanks in advance
and best regards,
Oshgnacknak

**Comment by Finleyyy** [comment]
Can you post the SQL Command of the manual creation of the table, please?
