### ISSUE TITLE
Error in Spigot 1.7.2

### ISSUE THREAD

**Issue by Pai2Chen** [BedwarsRel/BedwarsRel#990]
[12:44:48 ERROR]: Could not load 'plugins\BedwarsRel (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:355) [spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:135) [spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:437) [spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: null; could not determine a constructor for the tag !@UTF8;  in 'reader', line 10, column 7:
        - !@UTF8
          ^
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:477) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:276) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:247) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:442) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:325) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:145) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:306) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:461) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:412) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:188) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:181) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339.jar:git-Spigot-1339]
        ... 5 more

**Comment by Misat11** [comment]
for 1.7.2 you can't use latest version, you must use version 1.2.8
https://www.spigotmc.org/resources/bedwars-rel.6799/download?version=70670
